CREATE DATABASE EMPLOYEE;
USE EMPLOYEE;
CREATE TABLE DATA_SCIENCE_TEAM(
emp_id VARCHAR(100) NOT NULL,
first_name VARCHAR(100) NOT NULL,
last_name VARCHAR(100) NOT NULL,
gender VARCHAR(100) NOT NULL,
role VARCHAR(100) NULL,
dept VARCHAR(100) NOT NULL,
exp INT NOT NULL,
country VARCHAR(100) NOT NULL,
continent VARCHAR(100) NOT NULL,
PRIMARY KEY(emp_id));
CREATE TABLE EMPLOYEE_RECORD_TABLE(
emp_id VARCHAR(100) NOT NULL,
first_name VARCHAR(100) NOT NULL,
last_name VARCHAR(100) NOT NULL,
gender VARCHAR(100) NOT NULL,
role VARCHAR(100) NULL,
dept VARCHAR(100) NOT NULL,
exp INT NOT NULL,
country VARCHAR(100) NOT NULL,
continent VARCHAR(100) NOT NULL,
salary float NOT NULL,
emp_rating VARCHAR(100) NOT NULL,
manager_id VARCHAR(100) NOT NULL,
project_id VARCHAR(100) NOT NULL,
PRIMARY KEY(emp_id));
CREATE TABLE PROJECT_TABLE(
project_id VARCHAR(100) NOT NULL,
project_name VARCHAR(100) NOT NULL,
domain VARCHAR(100) NOT NULL,
start_date VARCHAR(100) NOT NULL,
closure_date VARCHAR(100) NOT NULL,
dev_qtr VARCHAR(100) NOT NULL,
status VARCHAR(100) NOT NULL,
PRIMARY KEY(project_id));
INSERT INTO DATA_SCIENCE_TEAM(emp_id,first_name,last_name,gender,role,dept,exp,country,continent)VALUES('E005','ERIC','HOFFMAN','M','LEAD DATA SCIENTIST','FINANCE','11','USA','NORTH AMERICA');
INSERT INTO EMPLOYEE_RECORD_TABLE(emp_id,first_name,last_name,gender,role,dept,exp,country,continent,salary,emp_rating,manager_id,project_id)VALUES('E001','ARTHUR','BLACK','M','PRESIDENT','ALL','20','USA','NORTH AMERICA','16500','5','NULL','NULL');
INSERT INTO PROJECT_TABLE(project_id,project_name,domain,start_date,closure_date,dev_qtr,status)VALUES('P103','DRUG DISCOVERY','HEALTHCARE','06/04/2021','20/06/2021','Q1','DONE');
SELECT emp_id,first_name,last_name,gender,dept FROM EMPLOYEE_RECORD_TABLE;
SELECT emp_id,first_name,last_name,gender,dept,emp_rating FROM EMPLOYEE_RECORD_TABLE WHERE emp_rating<'2';
SELECT emp_id,first_name,last_name,gender,dept,emp_rating FROM EMPLOYEE_RECORD_TABLE WHERE emp_rating>'4';
SELECT emp_id,first_name,last_name,gender,dept,emp_rating FROM EMPLOYEE_RECORD_TABLE WHERE emp_rating BETWEEN '2' AND '4';
SELECT first_name,last_name,dept,CONCAT(first_name," ",last_name) AS NAME FROM EMPLOYEE_RECORD_TABLE WHERE dept='finance';
SELECT emp_id,first_name,last_name,role,exp,COUNT(emp_id) AS EMP_COUNT FROM EMPLOYEE_RECORD_TABLE GROUP BY manager_id ORDER BY EMP_COUNT DESC;      
SELECT emp_id,first_name,last_name,role,dept FROM EMPLOYEE_RECORD_TABLE WHERE dept='healthcare' UNION SELECT emp_id,first_name,last_name,role,dept FROM EMPLOYEE_RECORD_TABLE WHERE dept='finance' ORDER BY dept,emp_id;
SELECT emp_id,first_name,last_name,role,dept,emp_rating,max(emp_rating) OVER(PARTITION BY dept) AS MAX_DEPT_RATING FROM EMPLOYEE_RECORD_TABLE ORDER BY dept;     
SELECT emp_id,first_name,last_name,role,MAX(salary),MIN(salary) FROM EMPLOYEE_RECORD_TABLE WHERE ROLE IN('PRESIDENT','LEAD DATA SCIENTIST','SENIOR DATA SCIENTIST','MANAGER','ASSOCIATE DATA SCIENTIST','JUNIOR DATA SCIENTIST') GROUP BY ROLE;   
SELECT emp_id,first_name,last_name,exp,RANK() OVER(ORDER BY EXP)EXP_RANK FROM EMPLOYEE_RECORD_TABLE;
CREATE VIEW EMPLOYEES_IN_VARIOUS_COUNTRIES AS
SELECT emp_id,first_name,last_name,country,salary FROM EMPLOYEE_RECORD_TABLE WHERE salary>6000;
SELECT*FROM EMPLOYEES_IN_VARIOUS_COUNTRIES;
SELECT emp_id,first_name,last_name,role,dept,exp FROM EMPLOYEE_RECORD_TABLE WHERE exp>10;
DELIMITER &&
CREATE PROCEDURE GET_EXP_DETAILS()
BEGIN
SELECT emp_id,first_name,last_name,exp FROM EMPLOYEE_RECORD_TABLE WHERE exp> '3';
END &&
CALL GET_EXP_DETAILS();
DELIMITER &&
CREATE FUNCTION EMPLOYEE_ROLE(
EXP INT
)
RETURNS VARCHAR(40)
DETERMINISTIC
BEGIN
DECLARE EMPLOYEE_ROLE VARCHAR(40);
IF EXP>12 AND 16 THEN
SET EMPLOYEE_ROLE='MANAGER';
ELSEIF EXP>12 AND 10 THEN
SET EMPLOYEE_ROLE='LEAD DATA SCIENTIST';
ELSEIF EXP>5 AND 10 THEN
SET EMPLOYEE_ROLE='SENIOR DATA SCIENTIST';
ELSEIF EXP>2 AND 5 THEN
SET EMPLOYEE_ROLE='ASSOCIATE DATA SCIENTIST';
ELSEIF EXP<=2 THEN
SET EMPLOYEE_ROLE='JUNIOR DATA SCIENTIS';
END IF;
RETURN (EMPLOYEE_ROLE);
END &&
SELECT EXP,EMPLOYEE_ROLE(EXP) FROM DATA_SCIENCE_TEAM;
CREATE INDEX idx_first_name
ON EMPLOYEE_RECORD_TABLE(FIRST_NAME(20));
SELECT * FROM EMPLOYEE_RECORD_TABLE
WHERE FIRST_NAME = 'ERIC';
UPDATE EMPLOYEE_RECORD_TABLE SET salary = ( SELECT SALARY + ( SELECT SALARY * .05 * emp_rating)) 
SELECT * FROM EMPLOYEE_RECORD_TABLE;

SELECT EMP_ID,FIRST_NAME,LAST_NAME,SALARY,COUNTRY,CONTINENT,
AVG(salary)OVER(PARTITION BY COUNTRY)AVG_salary_IN_COUNTRY,
AVG(salary)OVER(PARTITION BY CONTINENT)AVG_salary_IN_CONTINENT, 
COUNT(*)OVER(PARTITION BY COUNTRY)COUNT_IN_COUNTRY,
COUNT(*)OVER(PARTITION BY CONTINENT)COUNT_IN_CONTINENT
FROM employee_record_table;




